### PR TITLE
Automatic translations

### PR DESCRIPTION
**Pull request by Skaronator**
As stated in https://github.com/plexinc/plex-for-kodi/pull/75, it is possible to reuse the Plex-Web translations and here we go.

German looks good to me but there is a problem in the setting menu:

image

and could be fixed by moving the checkboxes more to the right

Translation compromise:
* "Force" -> "Forced"
* "This item is currently unavailable." -> "File unavailable"
* "Switch User" -> "Switch User..."
* "Shows" -> "TV Shows"
* "Camera Make" -> "Make"
* "Camera Model" -> "Model"
* "Shutter Speed" -> "Exposure"
* "Shutdown" -> "Power Off"
* "Hibernate" -> "Suspend"
* "Choose Version" -> "Select a version"
* "No Content available for this filter" -> "Can't find anything matching your current filters."
* "Server is not accessible. Please sign into your server and check your connection." -> "This server is offline or unreachable"

### CODE REVIEW

**Comment by Skaronator** [comment]
Added Czech as well, please validate @Pavuucek

**Comment by Skaronator** [comment]
Should be final now. @ruuk

**Comment by ruuk** [comment]
While we can definitely use all this code to generate the translation files, we can't merge it here with the repo structure as it is because that adds it to the addon structure. I'll probably move the actual addon to be a subdirectory of the repo, but I'll have to modify the add-on zip generation script that I use for all my add-ons a little. For now if you want to just PR the actual language files, we can at least merge those in.

**Comment by Skaronator** [comment]
Alrighty!

**Comment by Skaronator** [comment]
I've removed the Assets folder, should be ready for merge.

**Comment by ruuk** [comment]
A  few things left before merge.

- Let's lose the `.gitignore`
- The English file needs to be unchanged with the exception of `{0}` -> `{1}`
- Drop the Czech translation - see below

I seems like the code will in the future need to be changed to update existing files instead of just replacing them, otherwise we'll lose the strings from user submissions and the like. I'm going to merge in the Czech PR (#75) and modify the `{0}` -> `{1}` myself since the auto version is missing a number of strings. If you want to just drop the English file I'll do that one as well.

Unrelated to this PR - I'm thinking I'm going to create an empty branch and have you merge just the auto translation code to there. If I restructure the repo, we lose the ability to install the add-on directly from a GitHub zip download.

**Comment by Skaronator** [comment]
Other languages can be added with a simple .json file in this folder https://github.com/Skaronator/plex-for-kodi/tree/trans-script/Assets/Translation/PlexForKodi The script merge them together.

**Comment by ruuk** [comment]
> The script merge them together.

I now see that the strings I thought were missing were moved :smile:
So it will, in any case, still need to be modified so that the order of the strings is kept (i.e. in `msgctxt` numerical order).

Regarding the `.gitignore`, you can move the rules to one of the other locations that git allows, but the easiest probably would be to add .gitignore to `.gitignore`.

Also I want to make sure you know I appreciate the work you've done here. I'm not trying to be difficult :smile:

**Comment by Skaronator** [comment]
Already tried `.gitignore` inside of `.gitignore` but found a solution after quick [googling](https://stackoverflow.com/questions/767147/ignore-the-gitignore-file-itself).


> So it will, in any case, still need to be modified so that the order of the strings is kept (i.e. in msgctxt numerical order).
Alright added to the todo liste, also overwriting the Plex Web translations via the plex_for_kodi.json file is on that list.


I'd move the whole plugin to a subdirectory called `script.plex` and then re-add the `Assets` folder. (And would also add the .gitignore :P)

**Comment by ruuk** [comment]
If you'll remove the English translation (we'll never want to use the auto script on this) and the Czech translation I'll merge this. If there is some reason you think the auto Czech translation is better you can rebase or we can add it back in another PR.

**Comment by Skaronator** [comment]
>If you'll remove the English translation (we'll never want to use the auto script on this)
It would be the best way to handle english as well via the script.

**Pull request closed without merging**
