### PR TITLE
Spanish translations

### PR DESCRIPTION
**Pull request by rdcalle**
GHI (If applicable): #

## Description:
New Spanish translation content

## Checklist:
- [ ] I have based this PR against the develop branch

### CODE REVIEW

**Comment by rdcalle** [comment]
Could you please to accept my translation contribution? I hope could be on time before the new 0.1.7 release. Thanks.

**Comment by ruuk** [comment]
It won't be in 0.1.7 as that is already submitted to the Kodi repo. I'll merge it this week for the next release, which won't wait as long as the last one :smiley:.

**Comment by rdcalle** [comment]
I hope so! Thanks for the reply.

Salu2,
Ricardo Díaz.

**Comment by ruuk** [comment]
Thanks!

**Pull request merged**
