### PR TITLE
Use Unplayed/Played instead of Unwatched/Watched

### PR DESCRIPTION
**Pull request by pannal**
GHI (If applicable): #

## Description:
Recently the major Plex clients have changed the wording of Unwatched to Unplayed. This does the same.

## Checklist:
- [x] I have based this PR against the develop branch

### CODE REVIEW

**Comment by pannal** [comment]
Done!

**Comment by pannal** [comment]
Why is the unwatched filter all caps by the way?

**Comment by ruuk** [comment]
Thanks!

**Comment by ruuk** [comment]
> Why is the unwatched filter all caps by the way?
The short answer is because that's how the UX mocks had it :smile:. The longer answer is to set it apart from the normal filter options, as it's a toggle and is independent of the others.

**Comment by pannal** [comment]
OK, gotcha :)

**Pull request merged**
