### PR TITLE
Add Czech Language

### PR DESCRIPTION
**Pull request by Pavuucek**
This change is [Reviewable](https://reviewable.io/reviews/plexinc/plex-for-kodi/75)

### CODE REVIEW

**Comment by Skaronator** [comment]
Would be great if there is a way to automatically re-use the Plex Media Player translations.

**Comment by ruuk** [comment]
@Skaronator: Would be nice, but isn't possible :frowning_face:

**Comment by ruuk** [comment]
@Pavuucek: Could you move this PR to the develop branch? Thanks :smile:

**Comment by Skaronator** [comment]
@ruuk Well the Plex Media Server Translations on Transifex use the .po file extension for translation. You must rename the msgid to match the PMS translation IDs and then simply use the PMS translations. 

Probably a few strings are missing but they could be included in the PMS Transifex repo (or just handled in a new repo).

Here are the first few lines of the english file:
```
msgid "Photos"
msgstr "Photos"

msgid "Music"
msgstr "Music"

msgid "Home Videos"
msgstr "Home Videos"

msgid "Success"
msgstr "Success"

msgid "An error occurred"
msgstr "An error occurred"

msgid "An unexpected error occurred"
msgstr "An unexpected error occurred"

msgid "The server is not connected to plex.tv"
msgstr "The server is not connected to plex.tv"

msgid "Unknown sync list"
msgstr "Unknown sync list"

msgid "Unknown sync item"
msgstr "Unknown sync item"

msgid "Unknown item"
msgstr "Unknown item"
```

**Comment by Skaronator** [comment]
I was drilling a bit deeper. The Plex Web Transit Repo is better since it match more string with the Plex for Kodi repo.


Plex Web Translations are using a json with a array:

Here a example (german):
```
  "minute": "Minute",
  "minutes": "Minuten",
  "Play {1} before movies": "{1} vor Filmen abspielen",
  "12 hour format": "12-Stunden-Format",
  "24 hour format": "24-Stunden-Format",
  "Disabled": "Deaktiviert",
  "Cinema Trailers": "Kinotrailer",
```


The best way would be a little python script that convert the json to .po files.

**Comment by Skaronator** [comment]
FYI: Working on a script right now

**Comment by ruuk** [comment]
Went ahead and merged and rebased develop since master and develop had parity.

**Pull request merged**
