### PR TITLE
Fixed GUI not responding after public IP renewal

### PR DESCRIPTION
**Pull request by mkliche**
See problem discussed here: https://forums.plex.tv/discussion/289309/bug-pms-ip-change-not-handled-kodi-log-bloated-to-over-1-gb

### CODE REVIEW

**Comment by ruuk** [comment]
Thanks for the PR! I appreciate you taking the time to look at this. I'm away till Monday so I may not look at this before then. BTW I changed the base to `develop` :relaxed:

**Comment by dfekete** [comment]
@mkliche Thanks for taking the time to write a PR from the snippets in the Plex Forum! 
Could you incorporate the slight changes proposed by @ruuk above (with `plexapp.MANAGER.refreshResource(true)`) and rebase the PR to the develop branch? 

I tested it with these two commands and the refresh after IP renewal still works (although I still have some ideas for further improvements after that).

Then we could keep this PR (instead of me opening a second one) and get those fixes applied.

**Comment by pannal** [comment]
@dfekete @ruuk @mkliche should I take over, create a new PR, rebase on develop?

**Comment by dfekete** [comment]
@pannal thanks for tackling this issue, no objections from my side 👍

**Comment by ruuk** [comment]
Closing - fixed with PR #201

**Pull request closed without merging**
