### PR TITLE
playback speed

### PR DESCRIPTION
**Pull request by worldjoe**
GHI (If applicable): #296

## Checklist:
- [X] I have based this PR against the develop branch

### CODE REVIEW

**Comment by worldjoe** [comment]
This pull request does very little by itself. All it does is show the playback speed icon. It does not lalow for changing the playback speed. Users will still need to enable that feature for themselves. See more here:
https://forums.plex.tv/t/playback-speed/69044/147

**Comment by ruuk** [comment]
Thanks for the PR, but closing it as I've implemented it differently.

I've added a simple text display under the current playback time, both to eliminate the need for images and increase in addon size, and to allow handling any speed without needing to add more images.

**Comment by skoshy** [comment]
> Thanks for the PR, but closing it as I've implemented it differently.
> 
> I've added a simple text display under the current playback time, both to eliminate the need for images and increase in addon size, and to allow handling any speed without needing to add more images.

Is this currently live? I'm trying to change the playback speed in Plex on Kodi on my Android TV and can't find this text display.

**Comment by worldjoe** [comment]
> Is this currently live? I'm trying to change the playback speed in Plex on Kodi on my Android TV and can't find this text display.

Any release 0.2.1 or above will have this feature. The change was merged here: https://github.com/plexinc/plex-for-kodi/commit/680fc4f3e164dea7de615e07b517a8ee04f158d7

**Pull request closed without merging**
